language: node_js
node_js:
  - "8"
cache:
  yarn: true
install:
  - yarn
script:
  - yarn test
  - yarn build
branches:
  only:
    - master
    - "/^v\\d+\\.\\d+.*$/"
deploy:
  provider: npm
  email: aerdogan07@gmail.com
  api_key:
    secure: jUv7eTsI7GsNgkUkwpWyOcdddBOaCfIWxWzVknBWdYzuAezwqodbOYJ1UZzL35dXxJfR6cfNK5q2b92g1168RKrCSsdH+okQb9Ahe6ldeXBID/eJ1eOMSDICezHl6OZ5kyvVMY980voQmqytvrn9pph+ee38hGK2f1RdFHciPBJkyv5PwjPvaL9Qll/QbQt6IL0LMO0tnWlDNkbFsRS2a+8Yv6RYR0cWOfJq1t9ddKI4i3lPfnVz1ULV2h6b7GH6gajL5ssplQnA1tGmNyO/4kMryEYwnT/W1ielLaIhvJ/7WNl582M7HAF2OdG68vkusfQUixlAtmesX4PLWZkkeFZFFP4MF1hS69rtG6MK08LhRnSzlnn+HQgCX8csjddU3ieN/CvioBFcYoxdMnzGJPptLyT+dRZxY7okj/kADw2TvShLPlA6c6fPVkMkYrbWtr5RRXnW2piJCqQU9zPQtAkUi2N3yHaZUz9TEaDGZiqqV7TSSVMDwGLnDoUfIBas4dvId1BhOCEEcGBxpAyK8oQIGJSfj4WsAeyrVDfaJaePTXXkvu/kZ60FAeW0t9TWVTcLl+7bVRKySioaSEzvopfkVHL0r018eQx/L+RJT2nZ6ugbNAxGi8Rm0yFCcBoi15BRVpISO+daaHkOXc6Ne+F8BA0KyMLfiV2f9iMPETE=
  on:
    tags: true
    repo: alicanerdogan/react-data-cache
